### ISSUE TITLE
404 error for image ".block-system-main-menu-border.png"

### ISSUE THREAD

**Issue by sutibun** [backdrop-contrib/cleanish#3]
Installed cleanish theme and everything works as far as I can tell. However, when I checked the log messages, there are a ton of "page not found" errors for the following image.

`http://www.example.com/themes/cleanish/images/.block-system-main-menu-border.png`

I don't know if it matters or not but logging it here just in case.

PS: I like the theme ^_^)b

**Comment by klonos** [comment]
a) There is no such image in the [`/images`](https://github.com/backdrop-contrib/cleanish/tree/1.x-2.x/images) directory. I can only see a [nav-border.png](https://github.com/backdrop-contrib/cleanish/blob/1.x-2.x/images/nav-border.png).
b) Even if there was such an image there, it shouldn't have that leading dot in its filename.

The CSS rule that refers to that file is [this](https://github.com/backdrop-contrib/cleanish/blob/1.x-2.x/style.css#L557)

Thanx for reporting this @sutibun

**Comment by sutibun** [comment]
@klonos ^_^)b

**Comment by klonos** [comment]
OK, I just checked the equivalent .css file of the "parent" Drupal 7 [Clean Theme](https://www.drupal.org/project/clean_theme) and this seems to have occurred after some search & replace during the port.

Drupal:

```
/* navigation skin ***/
#main-menu ul.menu {
  float: left;
  margin-bottom: 1em;
}
#main-menu ul.menu a {
  height: 55px;
  line-height: 55px;
  font-size: 13px;
  font-weight: bold;
  color: #ddd;
  padding: 0 20px;
  text-decoration: none;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
#main-menu ul.menu li{
  padding-right: 2px;
  background-image: url("images/nav-border.png");
  background-position: right top;
  background-repeat: no-repeat;
}
```

Backdrop:

```
/* .block-system-main-menuigation skin ***/
.block-system-main-menu .content ul {
  float: left;
  margin-bottom: 1em;
}
.block-system-main-menu .content ul li a {
  height: 55px;
  line-height: 55px;
  font-size: 13px;
  font-weight: bold;
  color: #ddd;
  padding: 0 20px;
  text-decoration: none;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  background: none;
  border-radius: 0;
  padding: 4px 15px;
}


.block-system-main-menu .content ul li{
  padding-right: 2px;
  background-image: url("images/.block-system-main-menu-border.png");
  background-position: right top;
  background-repeat: no-repeat;
}
```

I think it is safe to assume that the file intended to be used here was `nav-border.png`

**Comment by docwilmot** [comment]
thanks, will check and fix

**Comment by sutibun** [comment]
_minor update:_ Replaced ".block-system-main-menu-border.png" with "nav-border.png" and at least from the quick look I gave, nothing seems wrong visually. More importantly, not getting any 404 errors anymore ^_^)b

**Comment by PaulHoza** [comment]
Well phooey.. here I thought I could actually contribute to something again after another contribution hiatus, but you folks are already on top of this.  :/

I have done the same as the above for now (just replaced the image src to point to "nav-border.png") and killed off the error.  More specifically I'm just overriding this CSS in my subtheme for now, which is working fine.

Thanks.

**Comment by docwilmot** [comment]
Thanks all, pushed fix as reported.

**Comment by PaulHoza** [comment]
Sweet!  Thank you.

Thanks for the theme, too.  Mucho helpo en me projecto.

**Comment by klonos** [comment]
Thanx. :+1:
